name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b
        add-to-path: true

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true


    - name: Prepare output directory
      run: mkdir -p out

    - name: build android-arm64
      run: |
        make build CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang GOOS=android GOARCH=arm64 NAME=ruleconverter-android-arm64
        make build-upx CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang GOOS=android GOARCH=arm64 NAME=ruleconverter-android-arm64-upx
    - name: Build linux-amd64
      run: |
        make build GOOS=linux GOARCH=amd64 NAME=ruleconverter-linux-amd64

    - name: Build linux-arm64
      run: |
        make build GOOS=linux GOARCH=arm64 NAME=ruleconverter-linux-arm64

    - name: Build linux-386
      run: |
        make build GOOS=linux GOARCH=386 NAME=ruleconverter-linux-386

    - name: Build windows-amd64
      run: |
        make build GOOS=windows GOARCH=amd64 NAME=ruleconverter-windows-amd64

    - name: Build windows-arm64
      run: |
        make build GOOS=windows GOARCH=arm64 NAME=ruleconverter-windows-arm64

    - name: Build darwin-amd64
      run: |
        make build GOOS=darwin GOARCH=amd64 NAME=ruleconverter-darwin-amd64

    - name: Build darwin-arm64
      run: |
        make build GOOS=darwin GOARCH=arm64 NAME=ruleconverter-darwin-arm64

    - name: Archive artifacts
      run: |
        cd out
        for file in ruleconverter-*; do
          if [ -f "$file" ]; then
            tar -czf "$file.tar.gz" "$file"
            rm "$file"
          fi
        done

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: out/ruleconverter-*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}